from turtle import *
speed(40)
bgcolor("Black")
color("white")
pensize(5)
begin_fill()
for i in range (8):
    left(180)
    for i in range(7):
        forward(125)
        right(135)
end_fill()
color("green")
penup()
forward (60)
left(90)
forward (125)
pendown()
right(90)
style=('courier',30,'italic')
write("HAPPY",font=style,align='right')
forward(10)
write("BIRTHDAY",font=style,align='left')
hideturtle()
