print('           , , , , ,')
print('           | | | | |')
print('         @%@%@%@%@%@%@')
print('         {   HAPPY   }')
print('         { BIRTHDAY! }')
print('       @%@%@%@%@%@%@%@%@')
print('       {               }')
print('       {               }')
print('       {               }')
print('     @%@%@%@%@%@%@%@%@%@%@')